// The tool list in docs/tools.md is generated by `npm run docs:tools` (test/docs-tools.mjs), never
// written by hand. These tests fail when running the generator would change docs/tools.md, i.e. when a
// tool was added, renamed, removed or re-described without regenerating the list.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { TOOLS_DOC, START, END, firstSentence, generateToolsDoc, renderToolTable, withToolTable } from './docs-tools.mjs';

const lf = (s) => s.replace(/\r\n/g, '\n');

test('docs/tools.md matches the live catalog (run `npm run docs:tools` if this fails)', async () => {
  const current = lf(await readFile(TOOLS_DOC, 'utf8'));
  assert.equal(current, await generateToolsDoc(), 'docs/tools.md is stale: run `npm run docs:tools` and commit the result');
});

test('the generated tool table lists every core tool plus the server-defined tools, one row each', async () => {
  const { buildCoreCatalog } = await import('../src/tools/index.mjs');
  const core = await buildCoreCatalog();
  const table = await renderToolTable();
  const rows = table.split('\n').filter((l) => /^\| `/.test(l));
  const names = rows.map((l) => l.match(/^\| `([^`]+)`/)[1]);
  const expected = [...core.definitions.map((d) => d.name), 'workspace_info', 'set_workspace', 'resume_bridge', 'list_packs'];
  assert.deepEqual([...names].sort(), [...expected].sort());
  assert.equal(new Set(names).size, names.length, 'a tool appears twice');
  for (const r of rows) assert.equal(r.split(/(?<!\\)\|/).length, 5, `malformed row: ${r}`);
});

test('firstSentence stops at the first real sentence end, not inside parentheses or after "e.g."', () => {
  assert.equal(firstSentence('Open an image. Returns the id.'), 'Open an image');
  assert.equal(firstSentence('Fit a view (e.g. L to RGB). Then more.'), 'Fit a view (e.g. L to RGB)');
  assert.equal(firstSentence('List processes, e.g. SCNR. Read-only.'), 'List processes, e.g. SCNR');
  assert.equal(firstSentence('Ends without a period'), 'Ends without a period');
  assert.equal(firstSentence('Values 1.5 and 2.0 are kept. Next.'), 'Values 1.5 and 2.0 are kept');
  assert.equal(firstSentence('A | B.'), 'A \\| B');
});

test('withToolTable replaces only the marked region and refuses a document without markers', () => {
  const doc = `intro\n${START}\nold\n${END}\noutro\n`;
  assert.equal(withToolTable(doc, 'NEW'), `intro\n${START}\nNEW\n${END}\noutro\n`);
  assert.throws(() => withToolTable('no markers here', 'NEW'), /must contain/);
});
