// ============================================================================
// `npm run docs:tools`: regenerates the tool list in docs/tools.md from the live
// catalog, between `<!-- tools:start -->` and `<!-- tools:end -->`. The list
// is never hand-written; test/docs-tools.test.mjs fails if running this would
// change docs/tools.md.
//
// "Live catalog" means exactly what a session with no packs serves:
// buildCoreCatalog() plus the server-defined tools (workspace_info,
// set_workspace, resume_bridge, list_packs), composed by the same
// assembleCatalog() serve() uses. Pack tools are not listed; they are not part
// of the connector.
//
// Groups come from the defining module's file name (src/tools/images.mjs ->
// "Images"), so adding a tool module never means editing a group map here.
// Tools defined by src/server.mjs itself are grouped as "Server".
//
// Node only, no shell: CI runs this on Windows too.
// ============================================================================
import { realpathSync } from 'node:fs';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { buildCoreCatalog } from '../src/tools/index.mjs';
import { assembleCatalog } from '../src/server.mjs';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const TOOLS_DIR = path.join(ROOT, 'src', 'tools');
export const TOOLS_DOC = path.join(ROOT, 'docs', 'tools.md');
export const START = '<!-- tools:start -->';
export const END = '<!-- tools:end -->';
const SERVER_GROUP = 'Server';

// "workspace-scan.mjs" -> "Workspace scan"
function groupLabel(file) {
  const words = path.basename(file, '.mjs').split(/[-_]/);
  const label = words.join(' ');
  return label.charAt(0).toUpperCase() + label.slice(1);
}

// The first sentence of a description: up to the first '.' that is outside parentheses, followed
// by whitespace or the end, and not part of an abbreviation like "e.g." / "i.e.". Trailing period
// dropped. Pipes escaped so the sentence cannot break the table row.
export function firstSentence(description) {
  const text = String(description).replace(/\s+/g, ' ').trim();
  let depth = 0;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (c === '(') depth++;
    else if (c === ')') depth = Math.max(0, depth - 1);
    else if (c === '.' && depth === 0 && (i === text.length - 1 || text[i + 1] === ' ')) {
      const before = text.slice(0, i + 1);
      if (/(?:^|\W)(?:e\.g|i\.e|etc|vs)\.$/i.test(before)) continue;
      return text.slice(0, i).replace(/\|/g, '\\|');
    }
  }
  return text.replace(/\.$/, '').replace(/\|/g, '\\|');
}

// Map every core tool name to the module file that defines it, by the same directory scan
// buildCoreCatalog() does (src/tools/*.mjs, except index.mjs).
async function moduleOfEachTool() {
  const files = (await readdir(TOOLS_DIR, { withFileTypes: true }))
    .filter((e) => e.isFile() && e.name.endsWith('.mjs') && e.name !== 'index.mjs')
    .map((e) => e.name)
    .sort();
  const owner = new Map();
  for (const file of files) {
    const mod = await import(pathToFileURL(path.join(TOOLS_DIR, file)).href);
    for (const t of Array.isArray(mod.tools) ? mod.tools : []) owner.set(t.name, file);
  }
  return owner;
}

// renderToolTable() -> the markdown between the markers (without the markers themselves).
export async function renderToolTable() {
  const core = await buildCoreCatalog();
  const { definitions } = assembleCatalog({ core, packs: [], packTools: [], resetBridge: () => {} });
  const owner = await moduleOfEachTool();

  const rows = definitions.map((d, index) => ({
    name: d.name,
    group: owner.has(d.name) ? groupLabel(owner.get(d.name)) : SERVER_GROUP,
    what: firstSentence(d.description),
    index,
  }));
  // Group order: alphabetical by code unit (not localeCompare, whose order depends on the host's
  // ICU locale -- the output must be byte-identical on every OS), "Server" last; within a group,
  // catalog (declaration) order.
  const key = (g) => [g === SERVER_GROUP ? 1 : 0, g];
  rows.sort((a, b) => {
    const [ka, kb] = [key(a.group), key(b.group)];
    if (ka[0] !== kb[0]) return ka[0] - kb[0];
    if (ka[1] !== kb[1]) return ka[1] < kb[1] ? -1 : 1;
    return a.index - b.index;
  });

  return [
    `${rows.length} tools. Generated by \`npm run docs:tools\` from the live catalog; do not edit by hand.`,
    '',
    '| Tool | Group | What it does |',
    '|---|---|---|',
    ...rows.map((r) => `| \`${r.name}\` | ${r.group} | ${r.what} |`),
  ].join('\n');
}

// withToolTable(doc, table) -> doc with the region between the markers replaced.
// Line endings of the input are normalized to LF (the repo's .gitattributes enforces LF).
export function withToolTable(doc, table) {
  const text = doc.replace(/\r\n/g, '\n');
  const start = text.indexOf(START);
  const end = text.indexOf(END);
  if (start === -1 || end === -1 || end < start) {
    throw new Error(`docs/tools.md must contain ${START} followed by ${END}`);
  }
  return `${text.slice(0, start + START.length)}\n${table}\n${text.slice(end)}`;
}

export async function generateToolsDoc() {
  return withToolTable(await readFile(TOOLS_DOC, 'utf8'), await renderToolTable());
}

async function main() {
  const current = await readFile(TOOLS_DOC, 'utf8');
  const next = await generateToolsDoc();
  if (next === current) {
    process.stdout.write('docs/tools.md is up to date.\n');
    return;
  }
  await writeFile(TOOLS_DOC, next, 'utf8');
  process.stdout.write('docs/tools.md regenerated.\n');
}

function isEntryPoint() {
  try {
    return Boolean(process.argv[1]) && pathToFileURL(realpathSync(process.argv[1])).href === import.meta.url;
  } catch {
    return false;
  }
}

if (isEntryPoint()) {
  main().catch((e) => {
    process.stderr.write(`docs:tools failed: ${e?.stack ?? e}\n`);
    process.exitCode = 1;
  });
}
